require 'rod'
require 'rlp/grammar'
require 'unicode_utils/downcase'
require 'unicode_utils/upcase'
require 'colors'

require 'rlp/corpus/corpus'
require 'rlp/corpus/model'
require 'rlp/corpus/source'
require 'rlp/corpus/document'
require 'rlp/corpus/sentence'
require 'rlp/corpus/segment'
